#version 460 core

layout(local_size_x=16,	local_size_y=16, local_size_z=1) in;

layout(std430, binding = 0) buffer Pos1
{
	vec4 Position_In[];
};

layout(std430, binding = 1) buffer Vel1
{
	vec4 Velocity_In[];
};

layout(std430, binding = 2) buffer Pos2
{
	vec4 Position_Out[];
};

layout(std430, binding = 3) buffer Vel2
{
	vec4 Velocity_Out[];
};

layout (binding = 4, offset = 0) uniform atomic_uint Count;

void main(void)
{
	
}